name: alist

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  # workflow_run:
  #   workflows:
  #     - t
  #   types:
  #     - completed  # 工作流完成后触发
  watch:
    # types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Check Workflow Status
      #   run: |
      #     workflow_runs=$(curl -s -X GET \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #       "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          
      #     isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "alist" and .status == "in_progress")')
          
      #     if [[ -n $isRunning ]]; then
      #       echo "Another workflow is already running. Aborting current workflow."
      #       exit 31
      #     else
      #       echo "No running workflows found. Continuing with the workflow execution."
      #     fi
      - name: rclone-install
        run: |
          # 安装 rclone
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          # curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          unzip rclone-*-amd64.zip
          cd rclone-*-linux-amd64
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
          # sudo apt-get install rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          echo "==========onedrive==========="
          rclone lsf onedrive:
          echo "==========dropbox==========="
          rclone lsf dropbox:

          sudo apt-get install fuse3
          sudo mkdir -p /dropbox
          sudo nohup rclone mount dropbox: /dropbox --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run alist container
        run: docker run -d --restart=unless-stopped -v /dropbox/self-hosted/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest
      - name: sleep
        run: |
          sudo sleep 1m    
      - name: Verify docker container is running
        run: docker ps
      - name: rclone-sync
        run: |
          echo "==========onedrive==========="
          rclone lsf onedrive:
          echo "==========dropbox==========="
          rclone lsf dropbox:
          echo "==========alist==========="
          rclone lsf alist:

          # echo "==========  onedrive:1  ==========="
          # rclone lsf  onedrive:1 --files-only --min-size 4G
          # echo "==========  onedrive:2  ==========="
          # rclone lsf  onedrive:2 --files-only --min-size 4G
          # echo "==========  onedrive:3  ==========="
          # rclone lsf  onedrive:3 --files-only --min-size 4G
          
          # sudo rclone sync onedrive:666 alist:123pan1Crypt/onedrive/666 -vv --fast-list --size-only --tpslimit 5 --transfers 2 --checkers 128 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs

          # sudo rclone sync onedrive:1 alist:123pan1Crypt/1 -vv --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs &
          rclone ls onedrive:2
          rclone ls alist:123pan2Crypt/2
          sudo rclone sync onedrive:2 alist:123pan2Crypt/2 -vv --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --onedrive-server-side-across-configs &
          # sudo rclone sync onedrive:3 alist:123pan2Crypt/3 -vv --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs &
          # sudo rclone sync onedrive:4 alist:baidupanCrypt/4 -vv --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs &
          # sudo rclone sync onedrive:5 alist:baidupanCrypt/5 -vv --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs &
          
          # # 在 wait 之前添加新的同步任务
          # sudo rclone sync onedrive: alist:123pan1Crypt/onedrive -vv \
          #     --exclude "1/**" \
          #     --exclude "2/**" \
          #     --exclude "3/**" \
          #     --exclude "4/**" \
          #     --exclude "5/**" \
          #     --tpslimit 5 --transfers 2 --checkers 4 --low-level-retries 10 --retries 5 --retries-sleep 10s --cache-chunk-size=64M --drive-chunk-size 64M --disable ListR --onedrive-server-side-across-configs &          
          # wait  # 等待所有任务完成
      - name: Verify docker container is running
        run: docker ps
      - name: sleep
        run: |
          sudo sleep 10m
      - name: send notification
        run: |
          curl -s -X POST https://api.telegram.org/bot'${{ secrets.TELEGRAM_BOT_TOKEN }}'/sendMessage -d chat_id='${{ secrets.TELEGRAM_CHAT_ID }}' -d text="github alist任务执行完毕"
