name: backup-github

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rclone-install
        run: |
          # 安装 rclone
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          # Rclone-Run
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          sudo mkdir /onedrive
          sudo nohup rclone mount onedrive: /onedrive --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sleep 3m
          cd /onedrive/backup/github
          pwd
          ls
          du -sh .
          
          # echo "==========开始同步==========="
          # # 根据[rclone的文档]，如果你想在同步的时候保留目标目录下的文件夹，你可以使用--backup-dir选项，指定一个备份目录，把要删除的文件移动到那里。例如，你可以这样执行：
          # # rclone sync --ignore-errors . i:backup/github -vv --backup-dir i:backup/github-old
          # # 这样，你就可以在i:backup/github目录下保留原来的文件夹，而把要删除的文件移动到i:backup/github-old目录下。希望这能帮到你。👍
          # rclone sync --ignore-errors . i:backup/github -vv --backup-dir i:backup/github-old
          # rclone size --ignore-errors i:backup/github -vv
          # echo "==========结束同步==========="

      # - name: Create backup directory
      #   run: |
      #     mkdir backup
      #     cd backup

      - name: List repositories
        run: |
          TOKEN="${{ secrets.PAT }}"
          curl -s -H "Authorization: token $TOKEN" "https://api.github.com/user/repos?type=all&per_page=100" | grep -e 'clone_url*' | cut -d \" -f 4 > repositories.txt
          sed -i "s|https://|https://$TOKEN@|g" repositories.txt

      - name: Clone repositories
        run: |
          while IFS= read -r repo; do
            echo "Cloning $repo..."
            git clone "$repo" || echo "git clone $repo 失败"
          done < repositories.txt

      - name: Pull repositories
        run: |
          while IFS= read -r repo; do
            dir=$(basename "$repo" .git)
            if [ -d "$dir" ]; then
              echo "Pulling $repo..."
              cd "$dir" || continue
              git pull origin main || echo "git pull $repo 失败"
              cd ..
            else
              echo "目录 $dir 不存在，跳过"
            fi
          done < repositories.txt

      - name: check backup
        run: |
          pwd
          ls
          du -sh .

      - name: send notification
        run: |
          curl -s -X POST https://api.telegram.org/bot'${{ secrets.TELEGRAM_BOT_TOKEN }}'/sendMessage -d chat_id='${{ secrets.TELEGRAM_CHAT_ID }}' -d text="github backup-github 任务执行结束"
