name: douyin
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: rclone-install
        run: |
          # 安装 rclone
          # curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          # curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          # unzip rclone-*-amd64.zip
          # cd rclone-*-linux-amd64
          # sudo mv rclone /usr/bin
          # sudo chmod +x /usr/bin/rclone
          sudo apt-get install rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          sudo apt-get install fuse3
          sudo mkdir /content/
          sudo mkdir /content/drive/
          sudo mkdir /content/drive/MyDrive/
          sudo mkdir /content/drive/MyDrive/my
          sudo mkdir /content/drive/MyDrive/1024
          sudo nohup rclone mount 1024: /content/drive/MyDrive/1024 --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/i
          sudo nohup rclone mount i: /content/drive/MyDrive/my/i --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/j
          sudo nohup rclone mount j: /content/drive/MyDrive/my/j --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/k
          sudo nohup rclone mount k: /content/drive/MyDrive/my/k --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/av1
          sudo nohup rclone mount av1: /content/drive/MyDrive/my/av1 --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/av2
          sudo nohup rclone mount av2: /content/drive/MyDrive/my/av2 --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          sudo mkdir /content/drive/MyDrive/my/dropbox
          sudo nohup rclone mount dropbox: /content/drive/MyDrive/my/dropbox --allow-non-empty --no-gzip-encoding --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
          echo "==========i==========="
          rclone lsf i:
          echo "==========j==========="
          rclone lsf j:
          echo "==========k==========="
          rclone lsf k:
          echo "==========o==========="
          rclone lsf o:
          echo "==========1024==========="
          rclone lsf 1024:
          echo "==========av1==========="
          rclone lsf av1:
          echo "==========av2==========="
          rclone lsf av2:
          echo "==========dropbox==========="
          rclone lsf dropbox:
      - name: run douyin
        run: |
          sudo apt-get update
          sudo timedatectl set-timezone Asia/Shanghai
          timedatectl

          cd /content/drive/MyDrive/my/i/backup/douyin/TikTokTool
          # 用户主页(非视频链接)
          # Saber
          # uid = https://www.douyin.com/user/MS4wLjABAAAADdqSYeEX6BTn_jQ_THNEDECn2oH5jkfUq1bLTHF6gzA
          python TikTokTool.py
          # Awu
          # https://v.douyin.com/iL1rgUuG
          python TikTokTool.py --uid https://v.douyin.com/iL1rgUuG --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}

          # 赵水莲
          # https://v.douyin.com/iL1rBxQN
          python TikTokTool.py --uid https://v.douyin.com/iL1rBxQN --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}
          # https://v.douyin.com/iL1kYmEk
          python TikTokTool.py --uid https://v.douyin.com/iL1kYmEk --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}

          # 何金玲
          # https://v.douyin.com/iL1rjFCd
          python TikTokTool.py --uid https://v.douyin.com/iL1rjFCd --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}

          # Auto parts-Jessy 🚗
          # https://v.douyin.com/i8oTnRfK
          python TikTokTool.py --uid https://v.douyin.com/i8oTnRfK --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}

          # 咩咩小i
          # uid = https://www.douyin.com/user/MS4wLjABAAAAwW6vDX_a-o7_I4pA1a01uctdLHVm_tjGoiIiDMSGHl7MeG_gc138NrNM_dJ7LRPK
          python TikTokTool.py --uid https://www.douyin.com/user/MS4wLjABAAAAwW6vDX_a-o7_I4pA1a01uctdLHVm_tjGoiIiDMSGHl7MeG_gc138NrNM_dJ7LRPK --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}
          # uid = https://v.douyin.com/i8tohAuj
          python TikTokTool.py --uid https://v.douyin.com/i8tohAuj --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}
          
          # 程程Cc
          # uid = https://v.douyin.com/i8toAVY6
          python TikTokTool.py --uid https://v.douyin.com/i8toAVY6 --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}
          # uid = https://v.douyin.com/i8to55Db
          python TikTokTool.py --uid https://v.douyin.com/i8to55Db --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}
          
          # 爆炸小脑袋
          # https://v.douyin.com/iL1hhtwy
          python TikTokTool.py --uid https://v.douyin.com/iL1hhtwy --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}   
          # https://v.douyin.com/iL1hLVud
          python TikTokTool.py --uid https://v.douyin.com/iL1hLVud --mode post --save ../Download --music yes --cover yes --desc yes --folderize yes --interval all --naming {create}_{desc}_{id} --cookie ${{ secrets.DOUYIN }}

          echo "github douyin 任务执行结束"
          curl -s -X POST https://api.telegram.org/bot'${{ secrets.TELEGRAM_BOT_TOKEN }}'/sendMessage -d chat_id='${{ secrets.TELEGRAM_CHAT_ID }}' -d text="github douyin 任务执行结束"
