name: emby2

on:
  schedule:
    # - cron: "0 3,9,15,21 * * *"
    - cron: "*/10 * * * *"
  workflow_dispatch:
  watch:
    # types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Status
        run: |
          workflow_runs=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          
          isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "emby2" and .status == "in_progress")')
          
          if [[ -n $isRunning ]]; then
            echo "Another workflow is already running. Aborting current workflow."
            exit 1
          else
            echo "No running workflows found. Continuing with the workflow execution."
          fi
      - name: rclone-install
        run: |
          # 安装 rclone
          # curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          unzip rclone-*-amd64.zip
          cd rclone-*-linux-amd64
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          sudo apt-get install fuse3
          sudo mkdir /content/
          sudo mkdir /content/drive/
          sudo mkdir /content/drive/MyDrive/
          sudo mkdir /content/drive/MyDrive/my
          sudo mkdir /content/drive/MyDrive/1024
          sudo nohup rclone --vfs-cache-mode full mount 1024: /content/drive/MyDrive/1024 &
          sudo mkdir /content/drive/MyDrive/my/i
          sudo nohup rclone --vfs-cache-mode full mount i: /content/drive/MyDrive/my/i &
          sudo mkdir /content/drive/MyDrive/my/j
          sudo nohup rclone --vfs-cache-mode full mount j: /content/drive/MyDrive/my/j &
          sudo mkdir /content/drive/MyDrive/my/k
          sudo nohup rclone --vfs-cache-mode full mount k: /content/drive/MyDrive/my/k &
          sudo mkdir /content/drive/MyDrive/my/av1
          sudo nohup rclone --vfs-cache-mode full mount av1: /content/drive/MyDrive/my/av1 &
          sudo mkdir /content/drive/MyDrive/my/av2
          sudo nohup rclone --vfs-cache-mode full mount av2: /content/drive/MyDrive/my/av2 &
      - name: install emby
        run: |
          curl -L -o emby-server.deb $(curl -s https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest | grep -oP '"browser_download_url": "\K(.*emby-server-deb.*amd64.deb)(?=")')
          sudo dpkg -i emby-server.deb
          sudo rm -rf /var/lib/emby/*
          sudo rm -r /var/lib/emby/
          if [ -d /var/lib/emby ]; then
            echo "Directory exists, exiting workflow"
            exit 31
          fi
          sudo ln -s /content/drive/MyDrive/my/j/emby2 /var/lib/emby
      - name: run emby
        run: |
          sudo nohup /opt/emby-server/bin/emby-server &
      - name: run cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo mkdir ~/.cloudflared/
          sudo rclone copy i:SyncBack/'${{ secrets.VD }}'/.cloudflared ~/.cloudflared -vv
          cloudflared tunnel route dns ee ee.'${{ secrets.VD }}'.eu.org
          cloudflared tunnel run --url http://127.0.0.1:8096 ee
