name: icloud

on:
  schedule:
    # - cron: "0 2,8,14,20 * * *"
    - cron: "0 * * * *"
  workflow_dispatch:
  # workflow_run:
  #   workflows:
  #     - t
  #   types:
  #     - completed  # 工作流完成后触发
  watch:
    # types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Status
        run: |
          workflow_runs=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          
          isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "icloud" and .status == "in_progress")')
          
          if [[ -n $isRunning ]]; then
            echo "Another workflow is already running. Aborting current workflow."
            exit 31
          else
            echo "No running workflows found. Continuing with the workflow execution."
          fi
      - name: rclone-install
        run: |
          # 安装 rclone
          # curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          # curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          # unzip rclone-*-amd64.zip
          # cd rclone-*-linux-amd64
          # sudo mv rclone /usr/bin
          # sudo chmod +x /usr/bin/rclone
          # sudo apt-get install rclone
          sudo -v ; curl https://rclone.org/install.sh | sudo bash -s beta
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          echo "==========onedrive==========="
          rclone lsf onedrive:
          echo "==========dropbox==========="
          rclone lsf dropbox:

          sudo rclone copy pikpak: icloud:pikpak -vv --ignore-existing --fast-list -tpslimit=10 --transfers=16 checkers=32 --drive-chunk-size=128M --multi-thread-cutoff=50M --multi-thread-streams=4 --retries=10 --low-level-retries=20
