name: openlist6

on:
  schedule:
    # - cron: "0 1,7,13,19 * * *"
    - cron: "*/5 * * * *"
  workflow_dispatch:
  # workflow_run:
  #   workflows:
  #     - t
  #   types:
  #     - completed  # 工作流完成后触发
  watch:
    # types: started

jobs:
  build:
    concurrency: openlist6-singleton 
    runs-on: ubuntu-latest
    # timeout-minutes: 60
    steps:
      - name: Check Workflow Status
        run: |
          # 获取当前工作流的运行ID
          CURRENT_RUN_ID=${{ github.run_id }}
    
          workflow_runs=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
    
          # 排除当前运行ID后检查是否有其他运行中的工作流
          otherRunning=$(echo "$workflow_runs" | jq --arg current_id "$CURRENT_RUN_ID" \
            '.workflow_runs[] | select(.name == "openlist2" and .status == "in_progress" and .id != ($current_id | tonumber))')
    
          if [[ -n $otherRunning ]]; then
            echo "Another workflow is already running. Aborting current workflow."
            exit 31
          else
            echo "No other running workflows found. Continuing."
          fi
      - name: rclone-install
        run: |
          # 安装 rclone
          # curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          unzip rclone-*-amd64.zip
          cd rclone-*-linux-amd64
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
          # sudo apt-get install rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          echo "==========onedrive==========="
          rclone lsf onedrive:
          echo "==========dropbox==========="
          rclone lsf dropbox:

          sudo apt-get install fuse3
          sudo mkdir -p /dropbox
          sudo nohup rclone mount dropbox: /dropbox --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run openlist container
        run: docker run -d --restart=unless-stopped -v /dropbox/self-hosted/openlist/data:/opt/openlist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="openlist" openlistteam/openlist:latest
      - name: sleep
        run: |
          sudo sleep 1m    
      - name: Verify docker container is running
        run: docker ps
      - name: rclone-sync
        run: |
          echo "==========onedrive==========="
          rclone lsf onedrive:
          echo "==========dropbox==========="
          rclone lsf dropbox:
          echo "==========openlist==========="
          rclone lsf openlist:wopan

          # echo "==========  onedrive:1  ==========="
          # rclone ls onedrive:1 --min-size 4G --size-only --order-by size
          # echo "==========  onedrive:2  ==========="
          # rclone ls onedrive:2 --min-size 4G --size-only --order-by size
          # echo "==========  onedrive:3  ==========="
          # rclone ls onedrive:3 --min-size 4G --size-only --order-by size
          # echo "==========  onedrive:4  ==========="
          # rclone ls onedrive:4 --min-size 4G --size-only --order-by size
          # echo "==========  onedrive:5  ==========="
          # rclone ls onedrive:5 --min-size 4G --size-only --order-by size
     
          # sudo rclone sync onedrive:1 openlist:baidupanCrypt/1 -vv --progress --fast-list --size-only --transfers 1 --checkers 32
          sudo rclone sync onedrive:2 openlist:wopanCrypt/2 -vv --progress
          sudo rclone sync onedrive:3 openlist:wopanCrypt/3 -vv --progress
          # sudo rclone sync onedrive:3 openlist:123pan1Crypt/3 -vv --progress --fast-list --size-only --transfers 1 --checkers 32
          # sudo rclone sync onedrive:4 openlist:123pan2Crypt/4 -vv --progress --fast-list --size-only --transfers 1 --checkers 32
          # sudo rclone sync onedrive:5 openlist:123pan2Crypt/5 -vv --progress --fast-list --size-only --transfers 1 --checkers 32
          
          # sudo rclone sync onedrive: openlist:baidupanCrypt/onedrive \
          #     --exclude "1/**" \
          #     --exclude "2/**" \
          #     --exclude "3/**" \
          #     --exclude "4/**" \
          #     --exclude "5/**" \
          #     -vv --progress --fast-list --size-only --transfers 1 --checkers 32 
      - name: Verify docker container is running
        run: docker ps
      - name: sleep
        run: |
          sudo sleep 10m
      - name: send notification
        run: |
          curl -s -X POST https://api.telegram.org/bot'${{ secrets.TELEGRAM_BOT_TOKEN }}'/sendMessage -d chat_id='${{ secrets.TELEGRAM_CHAT_ID }}' -d text="github alist 任务执行完毕"
