name: "rclone2"

on:
  schedule:
    # - cron: "0 2,8,14,20 * * *"
    - cron: "*/5 * * * *"
  workflow_dispatch:
  watch:
    # types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Status
        run: |
          workflow_runs=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          
          isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "rclone2" and .status == "in_progress")')
          
          if [[ -n $isRunning ]]; then
            echo "Another workflow is already running. Aborting current workflow."
            exit 31
          else
            echo "No running workflows found. Continuing with the workflow execution."
          fi
      - name: rclone-install
        run: |
          # 安装 rclone
          # curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          # curl -O https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip
          # unzip rclone-*-amd64.zip
          # cd rclone-*-linux-amd64
          # sudo mv rclone /usr/bin
          # sudo chmod +x /usr/bin/rclone
          sudo apt-get install rclone
      - name: rclone-config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: rclone-run
        run: |
          echo "==========i==========="
          rclone lsf i:
          echo "==========j==========="
          rclone lsf j:
          echo "==========k==========="
          rclone lsf k:
          echo "==========o==========="
          rclone lsf o:
          echo "==========1024==========="
          rclone lsf 1024:
          echo "==========av1==========="
          rclone lsf av1:
          echo "==========av2==========="
          rclone lsf av2:
          echo "==========dropbox==========="
          rclone lsf dropbox:
          echo "==========onedrive==========="
          rclone lsf onedrive:

          rclone sync j:2 onedrive:2 -vv --check-first --checkers=10 --transfers=10 --onedrive-chunk-size=100M --buffer-size=200M --cache-chunk-total-size=50G
