name: tailscale-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Enable Tailscale SSH
        run: sudo tailscale up --ssh --hostname=ts-test-${{ github.run_id }}

      - name: Stay online for verification
        run: sleep 240
