- name: Set permissions
  run: |
    if [ -d "./teslamate-grafana-data" ]; then
        sudo chown -R 472:472 ./teslamate-grafana-data/
        echo "teslamate-grafana-data 权限修改成功"
    else
        echo "警告: teslamate-grafana-data 目录不存在，跳过权限修改"
    fi
    
    if [ -d "./teslamate-db" ]; then
        sudo chown -R 999:999 ./teslamate-db/
        echo "teslamate-database-data 权限修改成功"
    else
        echo "警告: teslamate-db 目录不存在，跳过权限修改"
    fi

- name: Run teslamate container
  run: |
    sudo docker compose -p teslamate up -d

- name: Stop and backup
  run: |
    mkdir -p backup
    
    # 执行数据库备份
    sudo docker compose -p teslamate exec -T database pg_dump -U teslamate teslamate > ./backup/teslamate_$(date +"%Y-%m-%d").bck
    
    # 停止容器
    sudo docker compose -p teslamate stop
    sleep 1m
    
    # 保留最新的7个备份
    cd backup
    ls -t teslamate_*.bck | tail -n +8 | xargs -r sudo rm -f
    cd ..

- name: Compress and upload
  run: |
    # 压缩当前目录下的teslamate相关文件
    echo "正在压缩目录..."
    sudo tar -czf teslamate.tar.gz \
        teslamate-db \
        teslamate-grafana-data \
        import \
        mosquitto-conf \
        mosquitto-data \
        backup \
        docker-compose.yml
    
    # 上传到Dropbox
    echo "上传到Dropbox..."
    rclone copy -v teslamate.tar.gz dropbox:self-hosted/
    
    echo "完成 ✅"
